#!/usr/bin/env python

import os
import sys
import urllib2
import time
import random

from musette import environ

def readConfig(filePath):
    environ.read(filePath)
    proj = environ.str("project_tag")
    dir = environ.str("root_directory")
    start = environ.str("bug_start")
    end = environ.str("bug_end")
    return proj, dir, int(start), int(end)

def getRawContent(url):
    content = urllib2.urlopen(url).read()
    #add regular expression
    return content

def writeToFile(filePath, content):
    f = open(filePath,'w')
    f.write(content) # python will convert \n to os.linesep
    f.close()
    return


if __name__ == '__main__':
    if int(len(sys.argv)) < 2:
        print "config file path not given"
        os._exit(0)

    proj, dir, start, end = readConfig(sys.argv[1])

    for x in range(start, end):
        content = getRawContent("https://"+proj+".atlassian.net"+"/browse/WEBSITE-"+str(x)+"?jql=")
        writeToFile(dir+"/"+str(x), content)
        waitTime = random.randint(1, 60)
        print 'bug ',x,' data collected. Now will wait ', waitTime,' seconds'
        time.sleep(waitTime)

