#!/usr/bin/env python

__author__ = 'Rana'

from github import Github, UnknownObjectException
import time
import sys
import os

user = sys.argv[1]
if user == '':
    user = 'poise'

repo = sys.argv[2]
if repo == '':
    repo = 'python'
print user, ' ', repo
g = Github()
try:
    repo = g.get_repo(user+'/'+repo)
except UnknownObjectException as err:
    print 'repo not found', err
    os._exit(0)

contributors = repo.get_contributors()
for c in contributors:
    print c.name
    time.sleep(1)


